### ISSUE TITLE
게시판 api 만들기

### ISSUE THREAD

**Issue by dev-dykim** [dev-dykim/fastcampus-project-board-prac1#1]
api를 만든다.

* [x] API 설계
* [x] API 테스트 정의
* [x] API 구현
     * [x] 게시글 API
     * [x] 댓글 API

**Comment by DY0915** [comment]
api를 만든다.

* [] api 기능 조사하기
* [] 게시판 api
* [] 게시글 api
* [] 댓글 api

**Comment by dev-dykim** [comment]
api 설계 완료

* https://docs.google.com/spreadsheets/d/1eyunGU68ZwsCD4ccBnF89cMS3kDm5KYASnqRG9bSmvc/edit#gid=0
